name: "maqzテストリポジトリ"
short_name: "maqz test"
description: "maqzのテストリポジトリです。maqzは簡単にモダンなサイトを作成できるサイトビルダーです。"
author: "aqz / tamaina"
url: 
  path: "/maqz"
  host: "tamaina.github.io"
  scheme: https
pages_src: 
  path: "./pages/"
  src: "**/*.{html,htm,pug,md}"
page_namingrule: name
theme_color: 
  primary: "#ffffff"
  secondary: "#000000"
default: 
  template: default
social_media: 
  twitter: 
    stalk: t_ma1n
    share: true
    card: true
  LINE: 
    stalk: false
    share: true
  facebook: 
    stalk: false
    share: true
  flickr: 
    stalk: false
    share: false
  github: 
    stalk: tamaina
    share: false
  share_button: true
rss: false
disqus: false
ga: false
manifest: 
  start_url: "/"
  display: standalone
sw: "js|css|png|jpeg|jpg|svg|svgz|woff2"